### ISSUE TITLE
Error With Program Launch Due to Hardcoded char[] size

### ISSUE THREAD

**Issue by Izder456** [letrad/QuirkWM#8]
i do see that the error handling added to the program launch logic in [#7](https://github.com/letrad/QuirkWM/pull/7) actually always fails cos of my `$PATH` size

is probably cos the `char[]` buffer is too small, cos it complains about the string being too large, (i have lots of .local stuff in my `$PATH` and customization there)

there probably is a better way to stay memory-safe, than just hardcoding the size of the `char[]`.

I am testing on OpenBSD-Current with Xenocara, so Idk if this is also a problem on Linux or the other platforms targeted in the [Makefile](https://github.com/letrad/QuirkWM/blob/main/Makefile)

**Comment by NSG650** [comment]
Huh interesting. Could you please give me the steps to recreate the problem?

**Comment by Izder456** [comment]
Yep! Sure can!

here's the environment:
```bash
DISPLAY=:9.0
HOME=/home/izder456
LC_ALL=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LOGNAME=izder456
PATH=/home/izder456/.emacs.d/bin:/home/izder456/.cargo/bin:/home/izder456/.local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin
PWD=/home/izder456
SHELL=/usr/local/bin/zsh
```

here's the config.toml (at `$HOME/.config/quirk/config.toml`):
```toml
[wm]
border = 4
border-color = "#ebdbb2"
gap = 10

[pref]
term = "alacritty"
modkey = "Super"
```

Here's my system info:
```
OpenBSD CuteCorpBaSeD 7.3 GENERIC.MP#1324 amd64
```

& My error log:
```zsh
% Xephyr :9 -screen 1280x720 &
[1] 16201
% DISPLAY=:9.0 ./quirkwm
Failed to launch program: File name too long
Failed to launch program: No such file or directory
Failed to launch program: File name too long
Failed to launch program: File name too long
```

The error seems to only occur when i attempt to open Alacritty with my `Meta+t` binding (in this case, `Meta=Super`)

**Comment by letrad** [comment]
I may try to reproduce this, I have combined our PATHs together:
```
PATH=/home/letrad/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/home/letrad/.dotnet/tools:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/letrad/.local/share/JetBrains/Toolbox/scripts:/home/letrad/.emacs.d/bin:/home/letrad/.cargo/bin:/home/letrad/.local/bin:/bin:/sbin:/usr/sbin:/usr/X11R6/bin:/usr/local/sbin
```
I wil try with this.

**Comment by letrad** [comment]
```
Failed to launch program: No such file or directory
```
you're right. 

EDIT: No, it has nothing to do with the PATH. I believe I had not tested the code fully.

**Comment by letrad** [comment]
@NSG650 This was probably just a small mess up on your behalf, I've fixed it, take a look at the code and let me know if it looks good. If so, I'll merge it.

@Izder456 also try this on your system.

**Comment by Izder456** [comment]
@NSG650 @letrad 

LGTM!

**Comment by letrad** [comment]
Merged!
